### ISSUE TITLE
How do I get notified when user denies camera permission?

### ISSUE THREAD

**Issue by haemi** [twostraws/CodeScanner#27]
Is there a delegate method that handles this case?

**Comment by ralfebert** [comment]
Having the same problem - the permission error is currently unhandled:
https://github.com/twostraws/CodeScanner/blob/main/Sources/CodeScanner/CodeScanner.swift#L172

**Comment by twostraws** [comment]
I would hope this is reported back as one of the `ScanError` types, but if it isn't let me know!

**Comment by rholstad** [comment]
@twostraws there is no error reported when the user denies camera access on the initial permission request. Subsequent  initializations of the `AVCaptureDeviceInput` throw an exception with code [AVError.Code.applicationIsNotAuthorizedToUseDevice](https://developer.apple.com/documentation/avfoundation/averror/code/applicationisnotauthorizedtousedevice), which correctly filters back up the delegate chain.

You would need to explicitly manage the permission request rather than relying on the implicit request which is generated for you in the AVCaptureDeviceInput initializer. See [AVCaptureDevice.authorizationStatus(for:)](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624613-authorizationstatus) and [AVCaptureDevice.requestAccess(for:completionHandler:)](url). Then, put your setup code behind these requests to cover the initial denial.

**Comment by NathanFallet** [comment]
The completion now returns an error with `.permissionDenied` in this case.
